### ISSUE TITLE
Use of global Ember for Ember.String is deprecated

### ISSUE THREAD

**Issue by neilthawani** [ember-cli/ember-export-application-global#189]
We're getting a deprecation warning in our CCI build/test runner:

Using `Ember.String` is deprecated. Please import methods directly from `@ember/string`. [deprecation id: ember-string.from-ember-module] This will be removed in ember-source 5.0.0.

The docs for this migration are here:
https://deprecations.emberjs.com/v4.x/#toc_ember-string-from-ember-module

The replacement fix is:
`import { classify } from '@ember/string';`

`app/initializers/export-application-global.js`

and 

`tests/unit/initializers/export-application-global-test.js`

and the accompanying code line/syntax change.

**Comment by bertdeblock** [comment]
Do you actually use the functionality provided by `ember-export-application-global`? It was removed a while ago from the default blueprints, and I have the intention to deprecate and archive this repository: https://github.com/ember-cli/ember-export-application-global/pull/188.

**Comment by neilthawani** [comment]
Upon further inspection, we do not use this addon explicitly in our app. Cheers.
