### ISSUE TITLE
I cannot access the window.appname

### ISSUE THREAD

**Issue by shareit** [ember-cli/ember-export-application-global#7]
Here is my environment:
ember-cli  : 0.1.7
Ember      : 1.8.1
Ember Data : 1.0.0-beta.12
Handlebars : 1.3.0

The package.json file contains also this plugin name as follows: "ember-export-application-global": "^1.0.0". npm install and bower install was executed and all third-parties were installed. No jshint error is displayed when starting the server (execute ember server).

The config/environment.js file has the following content:
/* jshint node: true */

module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'appkit',
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created]
      testingProp: 'sdsd sdasd asdsd'
    },
    exportApplicationGlobal: true
  };

  ENV.hostname = 'http://api.hostname.com';
  ENV.namespace = 'v1';
  ENV.key = 'env_key';
  ENV.user_key = 'env_user_key'; // administrator
  ENV.is_external_user = false;
  ENV.URL = 'http://account1.hostname.com/';
  ENV.default_locale = 'en-US';
  ENV.tablet = false;

  if (environment === 'development') {
     //ENV.APP.LOG_RESOLVER = true;
     ENV.APP.LOG_ACTIVE_GENERATION = true;
     //ENV.APP.LOG_TRANSITIONS = true;
     //ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
     ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {

  }

  return ENV;
};

After the page is loaded, I checked the window.Appkit (Appkit is the name of my application) and I get an undefined value. 

I don'k know what is wrong or what I'm missing. I need a way to access the hostname property value from my ember application. 
Before to update the ember-cli on 0.1.17 I use the hostname property as window.AppkitENV.hostname, now the window.window.AppkitENV is undefined.

**Comment by clubajax** [comment]
This isn't working for me either, but I do see the code is injected as an initializer - so the bug is probably not in this plugin, it's probably in Ember.

**Comment by asleepinglion** [comment]
Thought it wasn't working as well, but issue was similar to @clubajax. It's because the initializer converts the modulePrefix using Ember.String.classify which changes the casing of the modulePrefix to UpperCamelCase.

**Comment by stefanpenner** [comment]
This works correctly on all apps I have come into contact with. If someone can provide a reproduction of a modern ember-cli app having trouble we can reproduce.
